
package bai4;

import bai5.nhanvien;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ADMIN
 */
public class lap4 extends javax.swing.JFrame {

    
    public lap4() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_name = new javax.swing.JTextField();
        cbo_nsinh = new javax.swing.JComboBox<>();
        rdo_ruou = new javax.swing.JRadioButton();
        rdo_bia = new javax.swing.JRadioButton();
        rdo_ngot = new javax.swing.JRadioButton();
        cbo_com = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_table = new javax.swing.JTable();
        btn_sxten = new javax.swing.JButton();
        btn_dotable = new javax.swing.JButton();
        btn_sxnsinh = new javax.swing.JButton();
        btn_them = new javax.swing.JButton();
        btn_sua = new javax.swing.JButton();
        btn_xoa = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("SỞ THÍCH CỦA TÔI");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("HỌ VÀ TÊN");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("NĂM SINH");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("ĐỒ UỐNG");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("CƠM");

        cbo_nsinh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbo_nsinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbo_nsinhActionPerformed(evt);
            }
        });

        rdo_ruou.setText("RƯỢU");

        rdo_bia.setText("BIA");
        rdo_bia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdo_biaActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdo_ngot);
        rdo_ngot.setText("NƯỚC NGỌT");

        cbo_com.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        tbl_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ho ten", "nam sinh", "do uong", "com"
            }
        ));
        tbl_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_table);

        btn_sxten.setText("SẮP XẾP HỌ TÊN");

        btn_dotable.setText("ĐỔ 6 ĐỐI TƯỢNG VÀO TABLE");
        btn_dotable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_dotableActionPerformed(evt);
            }
        });

        btn_sxnsinh.setText("SẮP XẾP THEO NĂM SINH");

        btn_them.setText("THÊM");
        btn_them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_themActionPerformed(evt);
            }
        });

        btn_sua.setText("SỬA");
        btn_sua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_suaActionPerformed(evt);
            }
        });

        btn_xoa.setText("XÓA");
        btn_xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_xoaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 694, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(79, 79, 79)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(rdo_ruou)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(rdo_bia)
                                        .addGap(18, 18, 18)
                                        .addComponent(rdo_ngot))
                                    .addComponent(cbo_com, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txt_name, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cbo_nsinh, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(47, 47, 47)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btn_sxten)
                                            .addComponent(btn_sxnsinh)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                        .addComponent(btn_them)
                                                        .addGap(39, 39, 39)
                                                        .addComponent(btn_sua))
                                                    .addComponent(btn_dotable))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btn_xoa)))))))))
                .addContainerGap(169, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txt_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(cbo_nsinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_dotable)
                        .addGap(21, 21, 21)
                        .addComponent(btn_sxten)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(rdo_ruou)
                            .addComponent(rdo_bia)
                            .addComponent(rdo_ngot)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btn_sxnsinh)))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_them)
                    .addComponent(btn_sua)
                    .addComponent(btn_xoa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cbo_com, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(214, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rdo_biaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdo_biaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdo_biaActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        this.setLocationRelativeTo(null);
        cbo_com.removeAllItems();
        cbo_nsinh.removeAllItems(); // xóa item cũ
        for (int i = 1990; i <= 2015; i++) {
            String t = i + "";
            // cách 2 String t1=String.valueOf(i);
            cbo_nsinh.addItem(t);
        }
        rdo_ruou.setSelected(true);
        rdo_ruou.isSelected();
        cbo_com.addItem("CƠM RANG");
        cbo_com.addItem("CƠM NẾP");
        cbo_com.addItem("CƠM XÔI");
        cbo_com.addItem("CƠM LAM");

    }//GEN-LAST:event_formWindowOpened

    private void btn_dotableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_dotableActionPerformed
        // TODO add your handling code here:
        this.formTable();
        this.fillTable();
    }//GEN-LAST:event_btn_dotableActionPerformed

    private void btn_themActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_themActionPerformed
        // TODO add your handling code here:
        this.addUser();
        this.fillTable();
        JOptionPane.showMessageDialog(this, "them thanh cong");
    }//GEN-LAST:event_btn_themActionPerformed

    private void cbo_nsinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbo_nsinhActionPerformed
        // TODO add your handling code here:
        

    }//GEN-LAST:event_cbo_nsinhActionPerformed

    private void btn_xoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_xoaActionPerformed
        // TODO add your handling code here:
        this.readForm();
        this.clearForm();
        this.fillTable();
        this.removeUser();
        JOptionPane.showMessageDialog(this, "xoa thanh cong");
    }//GEN-LAST:event_btn_xoaActionPerformed

    private void btn_suaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_suaActionPerformed
        // TODO add your handling code here:
        this.updateUser();
        this.fillTable();
        JOptionPane.showMessageDialog(this, "udate thanh cong");
    }//GEN-LAST:event_btn_suaActionPerformed

    private void tbl_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_tableMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_tbl_tableMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(lap4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(lap4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(lap4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(lap4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new lap4().setVisible(true);
            }
        });
    }

    public void formTable() {
        lap4class u1 = new lap4class("THINH", "2003", "NUOC NGOT", "COM RANG");
        lap4class u2 = new lap4class("TU", "2006", "NUOC NGOT", "COM LAM");
        lap4class u3 = new lap4class("HUY", "1999", "BIA", "XÔI");
        list.add(u1);
        list.add(u2);
        list.add(u3);
        fillTable();
    }
    ArrayList<lap4class> list = new ArrayList<>();

    void fillTable() {
        DefaultTableModel mol = (DefaultTableModel) tbl_table.getModel();

        for (lap4class x : list) {
            Object[] data = new Object[]{
                x.getHoTen(), x.getNamSinh(), x.getDoUong(), x.getCom()};
            mol.addRow(data);
        }
    }

    lap4class readForm() {
        String ten, namsinh, douong, com;
        ten = txt_name.getText();
        namsinh = cbo_nsinh.getToolTipText();
        com = cbo_com.getToolTipText();

        if (rdo_ruou.isSelected()) {
            douong = "RUOu";
        } else if (rdo_bia.isSelected()) {
            douong = "BIA";
        } else {
            douong = "NUOC NGOT";
        }
        return new lap4class(ten, namsinh, douong, com);
    }

    void writeForm(lap4class u) {
        txt_name.setText(u.getHoTen());
        cbo_nsinh.setToolTipText(u.getNamSinh());
        cbo_com.setToolTipText(u.getCom());
        if (u.getDoUong().equalsIgnoreCase("BIA")) {
            rdo_bia.setSelected(true);
        } else if (u.getDoUong().equalsIgnoreCase("RUOC")) {
            rdo_ruou.setSelected(true);
        } else {
            rdo_ngot.setSelected(true);
        }
    }
    
    
    void addUser() {
        list.add(readForm());
    }
    int getRow() {
        return tbl_table.getSelectedRow();
    }
    void removeUser() {
        int index = this.getRow();
        list.remove(index);
    }

    void clearForm() {
        txt_name.setText("");
        cbo_nsinh.setToolTipText("");
        rdo_bia.setText("");
        rdo_ruou.setText("");
        rdo_ngot.setText("");

        cbo_com.setToolTipText("");

    }
    void updateUser(){
    int index = this.getRow();
    lap4class u=this.readForm();
    list.set(index, u);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_dotable;
    private javax.swing.JButton btn_sua;
    private javax.swing.JButton btn_sxnsinh;
    private javax.swing.JButton btn_sxten;
    private javax.swing.JButton btn_them;
    private javax.swing.JButton btn_xoa;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbo_com;
    private javax.swing.JComboBox<String> cbo_nsinh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rdo_bia;
    private javax.swing.JRadioButton rdo_ngot;
    private javax.swing.JRadioButton rdo_ruou;
    private javax.swing.JTable tbl_table;
    private javax.swing.JTextField txt_name;
    // End of variables declaration//GEN-END:variables

    
}
