
package bai6;


import java.awt.Color;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ADMIN
 */
public class bailap6 extends javax.swing.JFrame implements Runnable{

    /**
     * Creates new form bailap6
     */
    public bailap6() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        lbl_ten = new javax.swing.JLabel();
        lbl_ngaysinh = new javax.swing.JLabel();
        lbl_name = new javax.swing.JLabel();
        lbl_gioitinh = new javax.swing.JLabel();
        lbl_cannang = new javax.swing.JLabel();
        lbl_qq = new javax.swing.JLabel();
        txt_name = new javax.swing.JTextField();
        txt_ns = new javax.swing.JTextField();
        rdo_nam = new javax.swing.JRadioButton();
        rdo_nu = new javax.swing.JRadioButton();
        txt_cannang = new javax.swing.JTextField();
        cbo_qq = new javax.swing.JComboBox<>();
        btn_ghi = new javax.swing.JButton();
        btn_them = new javax.swing.JButton();
        btn_mo = new javax.swing.JButton();
        btn_xoa = new javax.swing.JButton();
        btn_cn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_tt = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        lbl_ten.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_ten.setText("phạm quang thịnh");

        lbl_ngaysinh.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_ngaysinh.setText("Ngày Sinh");

        lbl_name.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_name.setText("Họ Tên");

        lbl_gioitinh.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_gioitinh.setText("Gioi Tính");

        lbl_cannang.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_cannang.setText("Cân nặng");

        lbl_qq.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_qq.setText("Quê Quán");

        buttonGroup1.add(rdo_nam);
        rdo_nam.setText("Nam");

        buttonGroup1.add(rdo_nu);
        rdo_nu.setText("Nữ");

        cbo_qq.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btn_ghi.setText("ghi file");
        btn_ghi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ghiActionPerformed(evt);
            }
        });

        btn_them.setText("thêm");
        btn_them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_themActionPerformed(evt);
            }
        });

        btn_mo.setText("mở file");
        btn_mo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_moActionPerformed(evt);
            }
        });

        btn_xoa.setText("xóa");
        btn_xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_xoaActionPerformed(evt);
            }
        });

        btn_cn.setText("cập nhật");

        tbl_tt.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "HỌ TÊN", "NGÀY SINH", "GIỚI TÍNH", "CÂN NẶNG", "QUÊ QUÁN", "SỨC KHỎE"
            }
        ));
        jScrollPane1.setViewportView(tbl_tt);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 561, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_ghi, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(67, 67, 67)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lbl_name)
                                .addComponent(lbl_ngaysinh)
                                .addComponent(lbl_gioitinh)
                                .addComponent(lbl_cannang)
                                .addComponent(lbl_qq))
                            .addGap(42, 42, 42)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(rdo_nam)
                                    .addGap(41, 41, 41)
                                    .addComponent(rdo_nu))
                                .addComponent(txt_name)
                                .addComponent(txt_ns, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE)
                                .addComponent(txt_cannang)
                                .addComponent(cbo_qq, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(101, 101, 101)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btn_cn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_xoa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_mo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(171, 171, 171)
                            .addComponent(lbl_ten, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(177, 177, 177)
                            .addComponent(btn_them, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(232, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_ten)
                    .addComponent(btn_them))
                .addGap(18, 18, 18)
                .addComponent(btn_ghi)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbl_name)
                        .addComponent(txt_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btn_mo)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_ngaysinh)
                            .addComponent(txt_ns, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btn_xoa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_gioitinh)
                    .addComponent(rdo_nam)
                    .addComponent(rdo_nu)
                    .addComponent(btn_cn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_cannang)
                    .addComponent(txt_cannang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_qq)
                    .addComponent(cbo_qq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        this.setLocationRelativeTo(null);
        
        cbo_qq.removeAllItems();
        cbo_qq.addItem("Hà Nội");
        cbo_qq.addItem("TP Hồ Chí Minh");
        cbo_qq.addItem("Đà Nẵng");
        cbo_qq.addItem("Tây Nguyên");

    }//GEN-LAST:event_formWindowOpened

    private void btn_themActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_themActionPerformed
        // TODO add your handling code here:
        this.add();
        this.check();
        this.fillTable();
    }//GEN-LAST:event_btn_themActionPerformed

    private void btn_ghiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ghiActionPerformed
        // TODO add your handling code here:
        write();
    }//GEN-LAST:event_btn_ghiActionPerformed

    private void btn_moActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_moActionPerformed
        // TODO add your handling code here:
        read();
    }//GEN-LAST:event_btn_moActionPerformed

    private void btn_xoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_xoaActionPerformed
        // TODO add your handling code here:
        this.xoa();
        this.fillTable();
    
    }//GEN-LAST:event_btn_xoaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(bailap6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(bailap6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(bailap6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(bailap6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new bailap6().setVisible(true);
            }
        });
        bailap6 dt = new bailap6();
        Thread th = new Thread(dt);
        th.start();
    }
    ArrayList<thongTin> list = new ArrayList<>();
    void fillTable(){
        DefaultTableModel mol = (DefaultTableModel) tbl_tt.getModel();
                mol.setRowCount(0);

        for(thongTin x : list){
        Object[] data = new Object[]{
            x.getHoTen(),x.getNgaySinh(),x.getGioiTinh(),x.getCanNang(),x.getQueQuan()
        };
        mol.addRow(data);
        }
      
    }
    thongTin readFrom(){
        String hoTen , ngaySinh,gioiTinh,canNang,queQuan;
        hoTen = txt_name.getText();
        ngaySinh = txt_ns.getText();
        if(rdo_nam.isSelected()){
            gioiTinh ="Nam";
        }else{
            gioiTinh = "Nữ";
        }
        canNang = txt_cannang.getText();
        queQuan = (String)cbo_qq.getSelectedItem();
        
       return new thongTin(hoTen, ngaySinh, gioiTinh, canNang, queQuan);
       
    }
    void add(){
        list.add(readFrom());
    }
        void writeForm(thongTin t) {
        txt_name.setText(t.getHoTen());
        txt_ns.setText(t.getNgaySinh());
        if (t.getGioiTinh().equalsIgnoreCase("Nam")) {
            rdo_nam.setSelected(true);
        } else {
            rdo_nu.setSelected(true);
        }
        txt_cannang.setText(t.getCanNang());
        cbo_qq.setToolTipText(t.getQueQuan());
    }
         void clear(){

        }
    void check(){
      String p_hoten = "[a-zA-Z ]+";
        if (txt_name.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "họ tên null");
            txt_name.requestFocus();
            txt_name.setBackground(Color.YELLOW);
            txt_name.setText("");
            return;
            
        }else
            if(txt_name.getText().matches(p_hoten)==false){
                JOptionPane.showMessageDialog(this, "họ tên sai định dạng");
                txt_name.requestFocus();
                txt_name.setBackground(Color.YELLOW);
                txt_name.setText("");
                return;
            
            }
 }
     void write(){
        try {
            
            JFileChooser fc = new JFileChooser();
            int chon = fc.showSaveDialog(null);
            if(chon==0)
            {
                String path = fc.getSelectedFile().getPath();
                FileOutputStream fo = new FileOutputStream(path);
                ObjectOutputStream ofo = new ObjectOutputStream(fo);
               ofo.writeObject(list);
               ofo.close();
               JOptionPane.showMessageDialog(this, "ghi file thanh cong");
              
               DefaultTableModel mol = (DefaultTableModel) tbl_tt.getModel();
               mol.setRowCount(0);
            }
            else{ 
                JOptionPane.showMessageDialog(this, "bạn không chọn lưu");
            }
        } catch (Exception e) {
           JOptionPane.showMessageDialog(this, "lỗi ghi file");
        }
    
    }
     void read(){
        try {
            JFileChooser fc = new JFileChooser();
            int chon = fc.showOpenDialog(null);
            if(chon==0){
               String path = fc.getSelectedFile().getPath();
                FileInputStream fi = new FileInputStream(path);
                ObjectInputStream ifi = new ObjectInputStream(fi);
                list = (ArrayList<thongTin>) ifi.readObject();
                ifi.close();
                fillTable();
            }else{
            JOptionPane.showMessageDialog(this, "bạn k chọn file để đọc");
            }
        } catch (Exception e) {
               JOptionPane.showMessageDialog(this, "lỗi ghi file");
                
        }
     }
     int getRow(){
     return tbl_tt.getSelectedRow();
     }
     void xoa(){
     int index = this.getRow();
     list.remove(index);
     }
     
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cn;
    private javax.swing.JButton btn_ghi;
    private javax.swing.JButton btn_mo;
    private javax.swing.JButton btn_them;
    private javax.swing.JButton btn_xoa;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbo_qq;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_cannang;
    private javax.swing.JLabel lbl_gioitinh;
    private javax.swing.JLabel lbl_name;
    private javax.swing.JLabel lbl_ngaysinh;
    private javax.swing.JLabel lbl_qq;
    private javax.swing.JLabel lbl_ten;
    private javax.swing.JRadioButton rdo_nam;
    private javax.swing.JRadioButton rdo_nu;
    private javax.swing.JTable tbl_tt;
    private javax.swing.JTextField txt_cannang;
    private javax.swing.JTextField txt_name;
    private javax.swing.JTextField txt_ns;
    // End of variables declaration//GEN-END:variables

    @Override
    public void run() {
       // throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    String ten;
        while (true) {            
            ten = lbl_ten.getText();
            String c = ten.substring(0,1);
        }
    }
}
