/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package thithu;

import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ADMIN
 */
public class thithu extends javax.swing.JFrame {

    /**
     * Creates new form thithu
     */
    public thithu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        lbl_ten = new javax.swing.JLabel();
        lbl_nsinh = new javax.swing.JLabel();
        lbl_qq = new javax.swing.JLabel();
        txt_ten = new javax.swing.JTextField();
        txt_nsinh = new javax.swing.JTextField();
        cbo_qq = new javax.swing.JComboBox<>();
        lbl_mau = new javax.swing.JLabel();
        rdo_a = new javax.swing.JRadioButton();
        rdo_b = new javax.swing.JRadioButton();
        rdo_ab = new javax.swing.JRadioButton();
        rdo_o = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_table = new javax.swing.JTable();
        btn_them = new javax.swing.JButton();
        btn_tim = new javax.swing.JButton();
        btn_doc = new javax.swing.JButton();
        btn_ghi = new javax.swing.JButton();
        btn_thoat = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setText("Thân Mẹ Yêu");

        lbl_ten.setText("HỌ TÊN");

        lbl_nsinh.setText("NGÀY SINH");

        lbl_qq.setText("QUÊ QUÁN");

        cbo_qq.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbo_qq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbo_qqActionPerformed(evt);
            }
        });

        lbl_mau.setText("NHÓM MÁU");

        buttonGroup1.add(rdo_a);
        rdo_a.setText("A");

        buttonGroup1.add(rdo_b);
        rdo_b.setText("B");

        buttonGroup1.add(rdo_ab);
        rdo_ab.setText("AB");

        buttonGroup1.add(rdo_o);
        rdo_o.setText("O");

        tbl_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_table);

        btn_them.setText("THÊM");
        btn_them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_themActionPerformed(evt);
            }
        });

        btn_tim.setText("TÌM");

        btn_doc.setText("ĐỌC FILE");
        btn_doc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_docActionPerformed(evt);
            }
        });

        btn_ghi.setText("GHI FILE");
        btn_ghi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ghiActionPerformed(evt);
            }
        });

        btn_thoat.setText("THOÁT");
        btn_thoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_thoatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(lbl_ten, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lbl_nsinh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lbl_qq, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(lbl_mau, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(32, 32, 32)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txt_ten, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txt_nsinh, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cbo_qq, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(rdo_a)
                                                .addGap(26, 26, 26)
                                                .addComponent(rdo_b)
                                                .addGap(18, 18, 18)
                                                .addComponent(rdo_ab)
                                                .addGap(18, 18, 18)
                                                .addComponent(rdo_o))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(btn_tim)
                                                .addGap(81, 81, 81)
                                                .addComponent(btn_doc)
                                                .addGap(40, 40, 40)
                                                .addComponent(btn_ghi)
                                                .addGap(32, 32, 32)
                                                .addComponent(btn_thoat))))))
                            .addComponent(btn_them)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 774, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_ten)
                    .addComponent(txt_ten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_nsinh)
                    .addComponent(txt_nsinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_qq)
                    .addComponent(cbo_qq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_mau)
                    .addComponent(rdo_a)
                    .addComponent(rdo_b)
                    .addComponent(rdo_ab)
                    .addComponent(rdo_o))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_them)
                    .addComponent(btn_tim)
                    .addComponent(btn_doc)
                    .addComponent(btn_ghi)
                    .addComponent(btn_thoat))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbo_qqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbo_qqActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbo_qqActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        this.setLocationRelativeTo(null);
        cbo_qq.removeAllItems();
        cbo_qq.addItem("Thái Bình");
        cbo_qq.addItem("Ba Vì");
        cbo_qq.addItem("Hà Nội");
        lilich l1 = new lilich("thịnh", "13 / 03 / 2003", "Ba Vì", "O");
        lilich l2 = new lilich("huy", "23 / 01 / 2003", "Hà Nội", "AB");
        lilich l3 = new lilich("huy", "23 / 01 / 2003", "Ba Vì", "AB");
        listll.add(l1);
        listll.add(l2);
        listll.add(l3);
        fillTable();
        tbl_table.setRowSelectionInterval(0, 2);

    }//GEN-LAST:event_formWindowOpened

    private void btn_themActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_themActionPerformed
        // TODO add your handling code here:
        addForm();
        fillTable();
    }//GEN-LAST:event_btn_themActionPerformed

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_formMouseClicked

    private void tbl_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_tableMouseClicked
        // TODO add your handling code here:
        int index = this.getRow();
        this.writeForm(listll.get(index));
    }//GEN-LAST:event_tbl_tableMouseClicked

    private void btn_thoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_thoatActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btn_thoatActionPerformed

    private void btn_docActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_docActionPerformed
        // TODO add your handling code here:
        read();
    }//GEN-LAST:event_btn_docActionPerformed

    private void btn_ghiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ghiActionPerformed
        // TODO add your handling code here:
        write();
    }//GEN-LAST:event_btn_ghiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(thithu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(thithu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(thithu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(thithu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new thithu().setVisible(true);
            }
        });
    }
    ArrayList<lilich> listll = new ArrayList<lilich>();

    void fillTable() {
        DefaultTableModel mol = (DefaultTableModel) tbl_table.getModel();
        mol.setRowCount(0);
        for (lilich x : listll) {
            Object[] data = new Object[]{
                x.getName(), x.getNgaySinh(), x.getQueQuan(), x.getNhomMau()
            };
            mol.addRow(data);
        }
    }

    lilich readFrom() {
        String ten, ngaysinh, quequan, nhommau;

        ten = txt_ten.getText();
        ngaysinh = txt_nsinh.getText();
        quequan = (String) cbo_qq.getSelectedItem();
        if (rdo_a.isSelected()) {
            nhommau = "A";
        } else if (rdo_b.isSelected()) {
            nhommau = "B";
        } else if (rdo_ab.isSelected()) {
            nhommau = "AB";
        } else {
            nhommau = "O";
        }
        return new lilich(ten, ngaysinh, quequan, nhommau);
    }

    void addForm() {
        listll.add(readFrom());

    }

    void writeForm(lilich ll) {
        txt_ten.setText(ll.getName());
        txt_nsinh.setText(ll.getNgaySinh());
        cbo_qq.setSelectedItem(ll.getQueQuan());
        if (ll.getNhomMau().equalsIgnoreCase("A")) {
            rdo_a.setSelected(true);
        } else if (ll.getNhomMau().equalsIgnoreCase("B")) {
            rdo_b.setSelected(true);
        } else if (ll.getNhomMau().equalsIgnoreCase("AB")) {
            rdo_ab.setSelected(true);
        } else {
            rdo_o.setSelected(true);
        }
    }

    int getRow() {
        return tbl_table.getSelectedRow();
    }

    void write() {
        try {
            JFileChooser fc = new JFileChooser();
            int chon = fc.showSaveDialog(null);
            if (chon == 0) {
                String  path = fc.getSelectedFile().getPath();
                FileOutputStream fo = new FileOutputStream(path);
                ObjectOutputStream ofo =new ObjectOutputStream(fo); 
                ofo.writeObject(listll);
                ofo.close();
                JOptionPane.showMessageDialog(this, "ghi thanh cong");
                DefaultTableModel mol = (DefaultTableModel) tbl_table.getModel();
                mol.setRowCount(0);
            }else{
                JOptionPane.showMessageDialog(this, "chua chon file");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "loi ghi file");
        }
    }
    void read(){
        try {
            JFileChooser fc = new JFileChooser();
            int chon = fc.showOpenDialog(null);
            if (chon == 0) {
                String  path = fc.getSelectedFile().getPath();
                FileInputStream fi = new FileInputStream(path);
                ObjectInputStream ifi =  new ObjectInputStream(fi); 
                listll = (ArrayList<lilich>) ifi.readObject();
                ifi.close();
                fillTable();
                }else{
                JOptionPane.showMessageDialog(this, "chua chon file de doc");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "loi ghi file");
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_doc;
    private javax.swing.JButton btn_ghi;
    private javax.swing.JButton btn_them;
    private javax.swing.JButton btn_thoat;
    private javax.swing.JButton btn_tim;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbo_qq;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_mau;
    private javax.swing.JLabel lbl_nsinh;
    private javax.swing.JLabel lbl_qq;
    private javax.swing.JLabel lbl_ten;
    private javax.swing.JRadioButton rdo_a;
    private javax.swing.JRadioButton rdo_ab;
    private javax.swing.JRadioButton rdo_b;
    private javax.swing.JRadioButton rdo_o;
    private javax.swing.JTable tbl_table;
    private javax.swing.JTextField txt_nsinh;
    private javax.swing.JTextField txt_ten;
    // End of variables declaration//GEN-END:variables
}
