/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bai3;

import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.ObjectInputStream;
import java.io.ObjectOutput;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ADMIN
 */
public class lap3 extends javax.swing.JFrame {

    /**
     * Creates new form lap3
     */
    public lap3() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lbl_name = new javax.swing.JLabel();
        txt_name = new javax.swing.JTextField();
        lbl_diem = new javax.swing.JLabel();
        txt_diem = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cbo_nganh = new javax.swing.JComboBox<>();
        lbl_hocluc = new javax.swing.JLabel();
        txt_hocluc = new javax.swing.JTextField();
        btn_them = new javax.swing.JButton();
        btn_xoa = new javax.swing.JButton();
        btn_capnhat = new javax.swing.JButton();
        btn_nhap = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_menu = new javax.swing.JTable();
        chk_thuong = new javax.swing.JCheckBox();
        btn_sxten = new javax.swing.JButton();
        btn_sxdiem = new javax.swing.JButton();
        btn_write = new javax.swing.JButton();
        btn_read = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("QUẢN LÍ SINH VIÊN");

        lbl_name.setText("HỌ VÀ TÊN");

        lbl_diem.setText("ĐIỂM");

        jLabel3.setText("NGÀNH");

        cbo_nganh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbo_nganh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbo_nganhActionPerformed(evt);
            }
        });

        lbl_hocluc.setText("HỌC LỰC");

        btn_them.setText("Thêm");
        btn_them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_themActionPerformed(evt);
            }
        });

        btn_xoa.setText("Xóa");
        btn_xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_xoaActionPerformed(evt);
            }
        });

        btn_capnhat.setText("Cập nhật");
        btn_capnhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_capnhatActionPerformed(evt);
            }
        });

        btn_nhap.setText("Nhập mới");

        tbl_menu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "HỌ VÀ TÊN", "ĐIỂM", "NGÀNH", "HỌC LỰC", "THƯỞNG"
            }
        ));
        jScrollPane1.setViewportView(tbl_menu);

        chk_thuong.setText("Có phần thưởng?");

        btn_sxten.setText("Sắp xếp theo tên");

        btn_sxdiem.setText("Sắp xếp theo điểm");

        btn_write.setText("WriteFile");
        btn_write.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_writeActionPerformed(evt);
            }
        });

        btn_read.setText("ReadFile");
        btn_read.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_readActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(448, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(437, 437, 437))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 575, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(lbl_name, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel3)
                                        .addComponent(lbl_diem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(lbl_hocluc))
                                .addGap(97, 97, 97)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(chk_thuong)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(btn_them)
                                                .addGap(34, 34, 34)
                                                .addComponent(btn_xoa)
                                                .addGap(40, 40, 40)
                                                .addComponent(btn_capnhat)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(btn_nhap))
                                            .addComponent(txt_diem, javax.swing.GroupLayout.DEFAULT_SIZE, 405, Short.MAX_VALUE)
                                            .addComponent(txt_name)
                                            .addComponent(cbo_nganh, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txt_hocluc))
                                        .addGap(50, 50, 50)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btn_write)
                                            .addComponent(btn_read)))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(243, 243, 243)
                        .addComponent(btn_sxten)
                        .addGap(43, 43, 43)
                        .addComponent(btn_sxdiem)))
                .addContainerGap(336, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_name)
                            .addComponent(txt_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(btn_write)))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbl_diem)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt_diem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_read)))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cbo_nganh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_hocluc)
                    .addComponent(txt_hocluc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(chk_thuong)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_them)
                    .addComponent(btn_xoa)
                    .addComponent(btn_capnhat)
                    .addComponent(btn_nhap))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_sxten)
                    .addComponent(btn_sxdiem))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_capnhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_capnhatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_capnhatActionPerformed

    private void cbo_nganhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbo_nganhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbo_nganhActionPerformed

    private void btn_themActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_themActionPerformed
        // TODO add your handling code here:       
        this.addUser();
        this.fillTable();
        JOptionPane.showMessageDialog(this, "thêm thành công");

    }//GEN-LAST:event_btn_themActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        this.setLocationRelativeTo(null);
        cbo_nganh.removeAllItems();
        cbo_nganh.addItem("ứng dụng phần mềm");
        cbo_nganh.addItem("Web");
        cbo_nganh.addItem("Marketing");
        cbo_nganh.addItem("Quản lí khách sạn");
        
        
        


    }//GEN-LAST:event_formWindowOpened

    private void btn_xoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_xoaActionPerformed
        // TODO add your handling code here:
        this.addUser();
        this.clearFrom();
        this.fillTable();
        JOptionPane.showMessageDialog(this, "xoa thanh cong");
    }//GEN-LAST:event_btn_xoaActionPerformed

    private void btn_writeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_writeActionPerformed
        // TODO add your handling code here:
        write();
    }//GEN-LAST:event_btn_writeActionPerformed

    private void btn_readActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_readActionPerformed
        // TODO add your handling code here:
        read();
    }//GEN-LAST:event_btn_readActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(lap3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(lap3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(lap3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(lap3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new lap3().setVisible(true);
            }
        });
    }
    ArrayList<User2> lstUser = new ArrayList<>();

    void fillTable() {
        DefaultTableModel mol = (DefaultTableModel) tbl_menu.getModel();
        mol.setRowCount(0);
        for (User2 x : lstUser) {
            Object[] data = new Object[]{
                x.getName(), x.getDiem(), x.getNganh(), x.getHocLuc()};

            mol.addRow(data);
        }
    }

    User2 readForm() {
        String ten, diem, hocluc;
        
        ten = txt_name.getText();
        diem = txt_diem.getText();
        hocluc = txt_hocluc.getText();

        return new User2(ten, diem, hocluc);
    }

    void writeForm(User2 u) {
        txt_name.setText(u.getName());
        txt_hocluc.setText(u.getHocLuc());
        
    }

    void addUser() {
        lstUser.add(readForm());
    }

    int getRow() {
        return tbl_menu.getSelectedRow();
    }

    void removeForm() {
        int index = this.getRow();
        lstUser.remove(index);
    }
    void clearFrom(){
        txt_name.getText();
        txt_diem.getText();
        txt_hocluc.getText();
      
    }
    void write(){//ghi du liệu ra đĩa
        try {
            // lấy ra đường dẫn của file
            JFileChooser fc = new JFileChooser();//cho phép chọn đường dẫn
            int chon = fc.showSaveDialog(null);
            if(chon==0)//co chọn ghi
            {
                String path = fc.getSelectedFile().getPath();
                FileOutputStream fo = new FileOutputStream(path);
                ObjectOutputStream ofo = new ObjectOutputStream(fo);
               ofo.writeObject(lstUser);// ghi ra list sinhvien ra file
               ofo.close();
               JOptionPane.showMessageDialog(this, "ghi file thanh cong");
               //xoa bang
               DefaultTableModel mol = (DefaultTableModel) tbl_menu.getModel();
               mol.setRowCount(0);
            }
            else{ //không chọn
                JOptionPane.showMessageDialog(this, "bạn không chọn lưu");
            }
        } catch (Exception e) {
           JOptionPane.showMessageDialog(this, "lỗi ghi file");
        }
    
    }
    void read(){//đọc file từ đĩa ra list
        try {
            JFileChooser fc = new JFileChooser();
            int chon = fc.showOpenDialog(null);
            if(chon==0){
               String path = fc.getSelectedFile().getPath();
                FileInputStream fi = new FileInputStream(path);
                ObjectInputStream ifi = new ObjectInputStream(fi);
                lstUser = (ArrayList<User2>) ifi.readObject();
                ifi.close();
                fillTable();
            }else{
            JOptionPane.showMessageDialog(this, "bạn k chọn file để đọc");
            }
        } catch (Exception e) {
               JOptionPane.showMessageDialog(this, "lỗi ghi file");
                
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_capnhat;
    private javax.swing.JButton btn_nhap;
    private javax.swing.JButton btn_read;
    private javax.swing.JButton btn_sxdiem;
    private javax.swing.JButton btn_sxten;
    private javax.swing.JButton btn_them;
    private javax.swing.JButton btn_write;
    private javax.swing.JButton btn_xoa;
    private javax.swing.JComboBox<String> cbo_nganh;
    private javax.swing.JCheckBox chk_thuong;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_diem;
    private javax.swing.JLabel lbl_hocluc;
    private javax.swing.JLabel lbl_name;
    private javax.swing.JTable tbl_menu;
    private javax.swing.JTextField txt_diem;
    private javax.swing.JTextField txt_hocluc;
    private javax.swing.JTextField txt_name;
    // End of variables declaration//GEN-END:variables

    private Object lstUser() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
