/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lan2;

import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ADMIN
 */
public class lan2 extends javax.swing.JFrame implements Runnable {

    static long ts, te;

    /**
     * Creates new form lan2
     */
    public lan2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_table = new javax.swing.JTable();
        lbl_hocts = new javax.swing.JLabel();
        lbl_thunhap = new javax.swing.JLabel();
        txt_ten = new javax.swing.JTextField();
        cbo_tendn = new javax.swing.JComboBox<>();
        rdo_co = new javax.swing.JRadioButton();
        rdo_khong = new javax.swing.JRadioButton();
        txt_thunhap = new javax.swing.JTextField();
        btn_them = new javax.swing.JButton();
        btn_sua = new javax.swing.JButton();
        btn_xoa = new javax.swing.JButton();
        btn_tim = new javax.swing.JButton();
        btn_ghi = new javax.swing.JButton();
        btn_doc = new javax.swing.JButton();
        lbl_time = new javax.swing.JLabel();
        lbl_time2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 102, 255));
        jLabel1.setText("công việc của tôi");

        jLabel2.setText("tên công việc");

        jLabel3.setText("tên doanh nghiệp");

        tbl_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        tbl_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_table);

        lbl_hocts.setText("học tiến sỹ");

        lbl_thunhap.setText("thu nhập");

        cbo_tendn.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        buttonGroup1.add(rdo_co);
        rdo_co.setText("có");

        buttonGroup1.add(rdo_khong);
        rdo_khong.setText("không");

        btn_them.setText("thêm");
        btn_them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_themActionPerformed(evt);
            }
        });

        btn_sua.setText("sửa");
        btn_sua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_suaActionPerformed(evt);
            }
        });

        btn_xoa.setText("xóa");
        btn_xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_xoaActionPerformed(evt);
            }
        });

        btn_tim.setText("tìm");

        btn_ghi.setText("ghi");
        btn_ghi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ghiActionPerformed(evt);
            }
        });

        btn_doc.setText("đọc");
        btn_doc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_docActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57)
                        .addComponent(lbl_time, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(76, 76, 76)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_them)
                            .addComponent(btn_sua)
                            .addComponent(btn_xoa))
                        .addGap(90, 90, 90)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_doc)
                            .addComponent(btn_ghi)
                            .addComponent(btn_tim)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 675, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                            .addComponent(lbl_hocts, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbl_thunhap, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rdo_co)
                                .addGap(35, 35, 35)
                                .addComponent(rdo_khong))
                            .addComponent(cbo_tendn, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_ten, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                            .addComponent(txt_thunhap))
                        .addGap(161, 161, 161)
                        .addComponent(lbl_time2, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(97, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn_them)
                        .addComponent(btn_tim))
                    .addComponent(lbl_time, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txt_ten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btn_sua))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(btn_ghi)))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cbo_tendn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_xoa)
                    .addComponent(btn_doc))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_hocts)
                    .addComponent(rdo_co)
                    .addComponent(rdo_khong))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_thunhap)
                            .addComponent(txt_thunhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(lbl_time2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        ts = Calendar.getInstance().getTimeInMillis() / 1000;
        this.setLocationRelativeTo(null);
        cbo_tendn.removeAllItems();
        cbo_tendn.addItem("fpt");
        cbo_tendn.addItem("viettel");
        cbo_tendn.addItem("nha cai");
      
        fillTable();
    }//GEN-LAST:event_formWindowOpened

    private void tbl_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_tableMouseClicked
        // TODO add your handling code here:
//        int index = this.getRow();
//        this.writeForm(listmj.get(index));
    }//GEN-LAST:event_tbl_tableMouseClicked

    private void btn_themActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_themActionPerformed
        // TODO add your handling code here:
        add();
        fillTable();
    }//GEN-LAST:event_btn_themActionPerformed

    private void btn_xoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_xoaActionPerformed
        // TODO add your handling code here:
        xoa();
        fillTable();
    }//GEN-LAST:event_btn_xoaActionPerformed

    private void btn_ghiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ghiActionPerformed
        // TODO add your handling code here:
       write();
    }//GEN-LAST:event_btn_ghiActionPerformed

    private void btn_docActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_docActionPerformed
        // TODO add your handling code here:
        read();
    }//GEN-LAST:event_btn_docActionPerformed

    private void btn_suaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_suaActionPerformed
        // TODO add your handling code here:
        sua();
        fillTable();

    }//GEN-LAST:event_btn_suaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(lan2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(lan2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(lan2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(lan2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new lan2().setVisible(true);
//            }
//        });
        lan2 td = new lan2();
        td.setVisible(true);
        Thread th = new Thread(td);

        th.start();
    }
    ArrayList<myjob> listmj = new ArrayList<myjob>();

    void fillTable() {
        DefaultTableModel mol = (DefaultTableModel) tbl_table.getModel();
        mol.setRowCount(0);
        for (myjob x : listmj) {
            Object[] data = new Object[]{
                x.getTenCV(), x.getTenDN(), x.getHocTienSy(), x.getThunhap(),x.getKetLuan()
            };
            mol.addRow(data);
        }
    }

    myjob readForm() {
        String tencv, tendn, hoctiensy;
        double thunhap;
        tencv = txt_ten.getText();
        tendn = (String) cbo_tendn.getSelectedItem();
        if (rdo_co.isSelected()) {
            hoctiensy = "có";
        } else {
            hoctiensy = "không";
        }
        thunhap = Double.parseDouble( txt_thunhap.getText());
        return new myjob(tencv, tendn, hoctiensy, thunhap);
    }
//
//    void writeForm(myjob mj) {
//        txt_ten.setText(mj.getTenCV());
//        cbo_tendn.setSelectedItem(mj.getTenDN());
//        if (mj.getHocTienSy().equalsIgnoreCase("có")) {
//            rdo_co.setSelected(true);
//        } else {
//            rdo_khong.setSelected(true);
//        }
//        txt_thunhap.setText(mj.getThunhap());
//    }

    int getRow() {
        return tbl_table.getSelectedRow();
    }

    void add() {
        listmj.add(readForm());
    }

    void xoa() {
        int index = this.getRow();
        listmj.remove(index);
    }

    void sua() {
        int index = this.getRow();
        myjob mj = this.readForm();
        listmj.set(index, mj);
    }
    void write(){
        try {
            JFileChooser fc =new JFileChooser();
            int chon = fc.showSaveDialog(null);
            if(chon==0){
            String path = fc.getSelectedFile().getPath();
            FileOutputStream fo = new FileOutputStream(path);
            ObjectOutputStream ofo = new ObjectOutputStream(fo);
            ofo.writeObject(listmj);
            ofo.close();
            JOptionPane.showMessageDialog(this, "ghi thanh cong");
            DefaultTableModel mol = (DefaultTableModel) tbl_table.getModel();
            mol.setRowCount(0);
            }else{
            JOptionPane.showMessageDialog(this, "gchua chon file");
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "loi ghi file");
        }
    }
    void read(){
    try {
            JFileChooser fc =new JFileChooser();
            int chon = fc.showOpenDialog(null);
            if(chon==0){
            String path = fc.getSelectedFile().getPath();
            FileInputStream fi = new FileInputStream(path);
            ObjectInputStream ifi = new ObjectInputStream(fi);
            listmj = (ArrayList<myjob>) ifi.readObject();
            ifi.close();
            fillTable();
            JOptionPane.showMessageDialog(this, "doc thanh cong");
            
            }else{
            JOptionPane.showMessageDialog(this, "chua chon file");
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "loi doc file");
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_doc;
    private javax.swing.JButton btn_ghi;
    private javax.swing.JButton btn_sua;
    private javax.swing.JButton btn_them;
    private javax.swing.JButton btn_tim;
    private javax.swing.JButton btn_xoa;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbo_tendn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_hocts;
    private javax.swing.JLabel lbl_thunhap;
    private javax.swing.JLabel lbl_time;
    private javax.swing.JLabel lbl_time2;
    private javax.swing.JRadioButton rdo_co;
    private javax.swing.JRadioButton rdo_khong;
    private javax.swing.JTable tbl_table;
    private javax.swing.JTextField txt_ten;
    private javax.swing.JTextField txt_thunhap;
    // End of variables declaration//GEN-END:variables

    @Override
    public void run() {
        while (true) {
            te = Calendar.getInstance().getTimeInMillis() / 1000;
            String time = (te - ts) + "";
            lbl_time.setText("thoi gian chay:" + time);
            String d,M,y,a1;
            int a;
            Calendar cl = Calendar.getInstance();
            d= cl.get(Calendar.HOUR_OF_DAY)+"";
            M= cl.get(Calendar.MINUTE)+"";
            y= cl.get(Calendar.SECOND)+"";
            a = cl.get(Calendar.AM_PM);
            if(a==1){
                a1="PM";
            }else{
            a1 ="AM";
            }
            lbl_time2.setText("thoi gian:"+d+ ":"+M+":"+y+ a1);
            try {
                Thread.sleep(1000);
            } catch (InterruptedException ex) {
                Logger.getLogger(lan2.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }
}
