/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bai7;


import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ADMIN
 */
public class lap7 extends javax.swing.JFrame implements Runnable{
static long ts,te;
    /**
     * Creates new form lap7
     */
    public lap7() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        lbl_id = new javax.swing.JLabel();
        lbl_tencv = new javax.swing.JLabel();
        txt_tencv = new javax.swing.JTextField();
        lbl_tendn = new javax.swing.JLabel();
        cbo_tendn = new javax.swing.JComboBox<>();
        lbl_hocts = new javax.swing.JLabel();
        rdo_yes = new javax.swing.JRadioButton();
        rdo_no = new javax.swing.JRadioButton();
        lbl_thunhap = new javax.swing.JLabel();
        txt_thunhap = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_table = new javax.swing.JTable();
        btn_them = new javax.swing.JButton();
        btn_sua = new javax.swing.JButton();
        btn_xoa = new javax.swing.JButton();
        btn_tim = new javax.swing.JButton();
        btn_sapxep = new javax.swing.JButton();
        btn_ghi = new javax.swing.JButton();
        btn_mo = new javax.swing.JButton();
        btn_luu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        lbl_id.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_id.setForeground(new java.awt.Color(102, 102, 255));
        lbl_id.setText("CÔNG VIỆC CỦA TÔI  ");

        lbl_tencv.setText("TÊN CÔNG VIỆC");

        lbl_tendn.setText("TÊN DOANH NGHIỆP");

        cbo_tendn.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lbl_hocts.setText("HỌC TIẾN SỸ");

        buttonGroup1.add(rdo_yes);
        rdo_yes.setText("CÓ");
        rdo_yes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdo_yesActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdo_no);
        rdo_no.setText("KHÔNG");
        rdo_no.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdo_noActionPerformed(evt);
            }
        });

        lbl_thunhap.setText("THU NHẬP");

        txt_thunhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_thunhapActionPerformed(evt);
            }
        });

        tbl_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "TÊN CV", "TÊN DN", "HỌC TIẾN SỸ", "THU NHẬP", "KẾTLUẬN"
            }
        ));
        jScrollPane1.setViewportView(tbl_table);

        btn_them.setText("THÊM");
        btn_them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_themActionPerformed(evt);
            }
        });

        btn_sua.setText("SỬA");
        btn_sua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_suaActionPerformed(evt);
            }
        });

        btn_xoa.setText("XÓA");
        btn_xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_xoaActionPerformed(evt);
            }
        });

        btn_tim.setText("TÌM");
        btn_tim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_timActionPerformed(evt);
            }
        });

        btn_sapxep.setText("SẮP XẾP");

        btn_ghi.setText("GHI FILE");
        btn_ghi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ghiActionPerformed(evt);
            }
        });

        btn_mo.setText("MỞ FILE");
        btn_mo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_moActionPerformed(evt);
            }
        });

        btn_luu.setText("LƯU");
        btn_luu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_luuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(325, 325, 325)
                        .addComponent(lbl_id, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lbl_tencv, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(32, 32, 32)
                                    .addComponent(txt_tencv))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(lbl_tendn)
                                    .addGap(18, 18, 18)
                                    .addComponent(cbo_tendn, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(lbl_hocts, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(rdo_yes)
                                    .addGap(64, 64, 64)
                                    .addComponent(rdo_no))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(lbl_thunhap, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txt_thunhap, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 766, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_tim)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_luu))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btn_xoa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_mo))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btn_sua)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_ghi))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_them)
                        .addGap(63, 63, 63)
                        .addComponent(btn_sapxep)))
                .addGap(104, 104, 104))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_id)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_them)
                    .addComponent(btn_sapxep))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_tencv)
                            .addComponent(txt_tencv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_sua)
                            .addComponent(btn_ghi))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_tendn)
                    .addComponent(cbo_tendn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_xoa)
                    .addComponent(btn_mo))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_hocts)
                    .addComponent(rdo_yes)
                    .addComponent(rdo_no))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_tim)
                    .addComponent(btn_luu))
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_thunhap)
                    .addComponent(txt_thunhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rdo_yesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdo_yesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdo_yesActionPerformed

    private void rdo_noActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdo_noActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdo_noActionPerformed

    private void txt_thunhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_thunhapActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_thunhapActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        this.setLocationRelativeTo(null);

        cbo_tendn.removeAllItems();
        cbo_tendn.addItem("FPT");
        cbo_tendn.addItem("VIETTEL");
        cbo_tendn.addItem("VNPT");
        ts = Calendar.getInstance().getTimeInMillis()/1000;// chuyển thành giây
    }//GEN-LAST:event_formWindowOpened

    private void btn_themActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_themActionPerformed
        // TODO add your handling code here:
        this.clearForm();
    }//GEN-LAST:event_btn_themActionPerformed

    private void btn_suaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_suaActionPerformed
        // TODO add your handling code here:
        this.sua();
        this.fillTable();
    }//GEN-LAST:event_btn_suaActionPerformed

    private void btn_xoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_xoaActionPerformed
        // TODO add your handling code here:
        this.xoa();
        this.fillTable();
    }//GEN-LAST:event_btn_xoaActionPerformed

    private void btn_ghiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ghiActionPerformed
        // TODO add your handling code here:
        write();
    }//GEN-LAST:event_btn_ghiActionPerformed

    private void btn_moActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_moActionPerformed
        // TODO add your handling code here:
        read();
    }//GEN-LAST:event_btn_moActionPerformed

    private void btn_luuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_luuActionPerformed
        // TODO add your handling code here:
        this.add();
        this.fillTable();
    }//GEN-LAST:event_btn_luuActionPerformed

    private void btn_timActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_timActionPerformed
        // TODO add your handling code here:
        String tam = JOptionPane.showInputDialog(this,"moi nhap ten cv");
//        //duyet toan bo list : neu tim thay
//        1. dua dt len form
//        2.danh du vao table
        tbl_table.setRowSelectionInterval(1, 1);
    }//GEN-LAST:event_btn_timActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(lap7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(lap7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(lap7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(lap7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new lap7().setVisible(true);
//            }
//        });
        lap7 dt =new lap7();
        dt.setVisible(true);
        Thread th = new Thread(dt);
        th.start();
    }
    ArrayList<MyJob> list = new ArrayList<>();
    void fillTable(){
        DefaultTableModel mol = (DefaultTableModel) tbl_table.getModel();
        mol.setRowCount(0);
        for(MyJob x : list){
            Object[] data = new Object[]{
                x.getTenCV(),x.getTenDN(),x.getHocTienSy(),x.getThuNhap(),x.getKetLuan()
            };
            mol.addRow(data);
        }
    }
    MyJob readForm(){
            String tenCV,tenDN,hocTienSy;
            double thuNhap;
            tenCV = txt_tencv.getText();
            tenDN = (String)cbo_tendn.getToolTipText();
            if(rdo_yes.isSelected()){
                hocTienSy ="CÓ";
            }else{
                hocTienSy ="KHÔNG";
            }
            thuNhap = Double.parseDouble(txt_thunhap.getText());
            
           return new MyJob(tenCV, tenDN, hocTienSy, thuNhap);
            }
    void writeForm(MyJob mj) {
        txt_tencv.setText(mj.getTenCV());
        cbo_tendn.getToolTipText();
        if (mj.getHocTienSy().equalsIgnoreCase("CÓ")) {
            rdo_no.setSelected(true);
        } else {
            rdo_yes.setSelected(true);
        }
        txt_thunhap.getText();
    }
    void add(){

        list.add(readForm());
    }
      int getRow(){
      return tbl_table.getSelectedRow();
      }
      void xoa(){
      int index = this.getRow();
      list.remove(index);
      }
      void sua(){
      int index = this.getRow();
      MyJob mj = this.readForm();
      list.set(index, mj);
      }
    void clearForm(){
        txt_tencv.setText("");
        txt_thunhap.setText("");  
    }
    void write(){
        try {
            
            JFileChooser fc = new JFileChooser();
            int chon = fc.showSaveDialog(null);
            if(chon==0)
            {
                String path = fc.getSelectedFile().getPath();
                FileOutputStream fo = new FileOutputStream(path);
                ObjectOutputStream ofo = new ObjectOutputStream(fo);
               ofo.writeObject(list);
               ofo.close();
               JOptionPane.showMessageDialog(this, "ghi file thanh cong");
              
               DefaultTableModel mol = (DefaultTableModel) tbl_table.getModel();
               mol.setRowCount(0);
            }
            else{ 
                JOptionPane.showMessageDialog(this, "bạn không chọn lưu");
            }
        } catch (Exception e) {
           JOptionPane.showMessageDialog(this, "lỗi ghi file");
        }
    
    }
     void read(){
        try {
            JFileChooser fc = new JFileChooser();
            int chon = fc.showOpenDialog(null);
            if(chon==0){
               String path = fc.getSelectedFile().getPath();
                FileInputStream fi = new FileInputStream(path);
                ObjectInputStream ifi = new ObjectInputStream(fi);
                list = (ArrayList<MyJob>) ifi.readObject();
                ifi.close();
                fillTable();
            }else{
            JOptionPane.showMessageDialog(this, "bạn k chọn file để đọc");
            }
        } catch (Exception e) {
               JOptionPane.showMessageDialog(this, "lỗi ghi file");
                
        }
     }
     
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_ghi;
    private javax.swing.JButton btn_luu;
    private javax.swing.JButton btn_mo;
    private javax.swing.JButton btn_sapxep;
    private javax.swing.JButton btn_sua;
    private javax.swing.JButton btn_them;
    private javax.swing.JButton btn_tim;
    private javax.swing.JButton btn_xoa;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbo_tendn;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_hocts;
    private javax.swing.JLabel lbl_id;
    private javax.swing.JLabel lbl_tencv;
    private javax.swing.JLabel lbl_tendn;
    private javax.swing.JLabel lbl_thunhap;
    private javax.swing.JRadioButton rdo_no;
    private javax.swing.JRadioButton rdo_yes;
    private javax.swing.JTable tbl_table;
    private javax.swing.JTextField txt_tencv;
    private javax.swing.JTextField txt_thunhap;
    // End of variables declaration//GEN-END:variables

    @Override
    public void run() {
//        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    String name;
        while(true){
             name=lbl_id.getText();
             //cắt kí tự đầu tiên
             String c = name.substring(0,1);
             //cắt các kí tự còn lại
             name = name.substring(1) + c;
             lbl_id.setText(name);// set lại cái tên đã bị cắt
            try {
                Thread.sleep(1000);//dừng 1s
            } catch (InterruptedException ex) {
                Logger.getLogger(lap7.class.getName()).log(Level.SEVERE, null, ex);
            }
        //throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
    }

}